### ISSUE TITLE
Organizing memory storage+retrieval

### ISSUE THREAD

**Issue by matbeedotcom** [caspianmoon/memoripy#2]
What is the go-to method to ensuring we keep memories organized to some form of unique identifier/session?

**Comment by caspianmoon** [comment]
The library keeps memories organized by associating each interaction with a unique identifier (id) generated as a UUID. This ensures every interaction can be referenced and retrieved independently. Beyond the id, interactions are categorized into short-term and long-term memory based on usage frequency and relevance.
