### ISSUE TITLE
Support for "any" embedding/chat model

### ISSUE THREAD

**Issue by FrancescoCaracciolo** [caspianmoon/memoripy#3]
Hello, I would like to propose a way of supporting every embedding or chat model instead of limiting to OpenAI and Ollama.
```mermaid
classDiagram
    EmbeddingModel <|-- OpenAIEmbeddingModel
    EmbeddingModel<|-- OllamaEmbeddingModel
    ChatModel <|-- OpenAIChatModel
    ChatModel <|-- OllamaChatModel 

    class EmbeddingModel {
        + dimension
        + embed(str text) np.array
    }

    class ChatModel {
        + extract_concepts(text) list
        + generate_text(history) str
    }

    class OpenAIChatModel {

    }

    class OllamaChatModel {

    }

    class OpenAIEmbeddingModel {

    }

    class OllamaEmbeddingModel {
        
    }
```

Obviously, additional/different methods might be specified.
Advantages of this structure:
- Ability for the user to create subclasses of `EmbeddingModel` and `ChatModel`
- More modular, easier to extend, update and read

**Comment by caspianmoon** [comment]
Thanks! I have already started working on a method to implement support for other embedding and chat models.
