### ISSUE TITLE
Incompatibility when installing

### ISSUE THREAD

**Issue by paulsybrandy** [caspianmoon/memoripy#7]
When I try to install via pip install memoripy I get incompatible versions of three requirements as seen below. I tried uninstalling the three and running the command again hoping it would install the versions it wanted but it just reinstalled the versions I had and then just gave me the exact same error. What is going on?!

C:\Users\pauln>pip install memoripy
Requirement already satisfied: memoripy in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (0.1.1)
Requirement already satisfied: aiohappyeyeballs==2.4.3 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (2.4.3)
Requirement already satisfied: aiohttp==3.10.10 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (3.10.10)
Requirement already satisfied: aiosignal==1.3.1 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.3.1)
Requirement already satisfied: annotated-types==0.7.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.7.0)
Requirement already satisfied: anyio==4.6.2.post1 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (4.6.2.post1)
Requirement already satisfied: attrs==24.2.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (24.2.0)
Requirement already satisfied: certifi==2024.8.30 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (2024.8.30)
Requirement already satisfied: charset-normalizer==3.4.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (3.4.0)
Requirement already satisfied: distro==1.9.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.9.0)
Requirement already satisfied: faiss-cpu==1.8.0.post1 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.8.0.post1)
Requirement already satisfied: frozenlist==1.5.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.5.0)
Requirement already satisfied: h11==0.14.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.14.0)
Requirement already satisfied: httpcore==1.0.6 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.0.6)
Requirement already satisfied: httpx==0.27.2 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.27.2)
Requirement already satisfied: idna==3.10 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (3.10)
Requirement already satisfied: jiter==0.7.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.7.0)
Requirement already satisfied: joblib==1.4.2 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.4.2)
Requirement already satisfied: jsonpatch==1.33 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.33)
Requirement already satisfied: jsonpointer==3.0.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (3.0.0)
Collecting langchain==0.3.7 (from memoripy)
  Using cached langchain-0.3.7-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: langchain-core==0.3.15 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.3.15)
Requirement already satisfied: langchain-ollama==0.2.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.2.0)
Requirement already satisfied: langchain-openai==0.2.5 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.2.5)
Requirement already satisfied: langchain-text-splitters==0.3.2 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.3.2)
Requirement already satisfied: langsmith==0.1.139 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.1.139)
Requirement already satisfied: multidict==6.1.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (6.1.0)
Requirement already satisfied: networkx==3.4.2 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (3.4.2)
Requirement already satisfied: numpy==1.26.4 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.26.4)
Requirement already satisfied: ollama==0.3.3 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.3.3)
Requirement already satisfied: openai==1.53.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.53.0)
Requirement already satisfied: orjson==3.10.11 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (3.10.11)
Requirement already satisfied: packaging==24.1 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (24.1)
Requirement already satisfied: propcache==0.2.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.2.0)
Requirement already satisfied: pydantic==2.9.2 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (2.9.2)
Requirement already satisfied: pydantic-core==2.23.4 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (2.23.4)
Requirement already satisfied: PyYAML==6.0.2 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (6.0.2)
Requirement already satisfied: regex==2024.9.11 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (2024.9.11)
Requirement already satisfied: requests==2.32.3 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (2.32.3)
Requirement already satisfied: requests-toolbelt==1.0.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.0.0)
Requirement already satisfied: scikit-learn==1.5.2 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.5.2)
Requirement already satisfied: scipy==1.14.1 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.14.1)
Requirement already satisfied: setuptools==75.3.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (75.3.0)
Requirement already satisfied: sniffio==1.3.1 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.3.1)
Requirement already satisfied: SQLAlchemy==2.0.36 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (2.0.36)
Requirement already satisfied: tenacity==9.0.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (9.0.0)
Requirement already satisfied: threadpoolctl==3.5.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (3.5.0)
Requirement already satisfied: tiktoken==0.8.0 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (0.8.0)
Requirement already satisfied: tqdm==4.66.6 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (4.66.6)
Requirement already satisfied: typing-extensions==4.12.2 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (4.12.2)
Requirement already satisfied: urllib3==2.2.3 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (2.2.3)
Requirement already satisfied: yarl==1.17.1 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from memoripy) (1.17.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from SQLAlchemy==2.0.36->memoripy) (3.1.1)
Requirement already satisfied: colorama in c:\users\pauln\appdata\local\programs\python\python312\lib\site-packages (from tqdm==4.66.6->memoripy) (0.4.6)
Using cached langchain-0.3.7-py3-none-any.whl (1.0 MB)
Installing collected packages: langchain
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-community 0.2.12 requires langchain<0.3.0,>=0.2.13, but you have langchain 0.3.7 which is incompatible.
langchain-community 0.2.12 requires langchain-core<0.3.0,>=0.2.30, but you have langchain-core 0.3.15 which is incompatible.
langchain-community 0.2.12 requires tenacity!=8.4.0,<9.0.0,>=8.1.0, but you have tenacity 9.0.0 which is incompatible.
Successfully installed langchain-0.3.7

**Comment by caspianmoon** [comment]
Hi paulsybrandy,

Thank you for reporting this! The issue is due to dependency conflicts between memoripy and langchain-community. I recommend using a clean virtual environment to avoid these conflicts. If that’s not possible, you may need to adjust the installed package versions manually. Let me know if you run into issues with a clean env.

**Comment by paulsybrandy** [comment]
@caspianmoon that worked nicely. Not sure why I did not consider just creating a new venv. Thanks for your help. Closing.

**Comment by paulsybrandy** [comment]
Thanks.

**Comment by caspianmoon** [comment]
You're welcome
